### ISSUE TITLE
bound must be positive

### ISSUE THREAD

**Issue by fonkfader** [FabioZumbi12/InfernalMobs#2]
using latest for 1.16.1 with paper spigot git-Paper-39 (1.16.1) :
`java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_252]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilities(infernal_mobs.java:1861) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilitiesAmount(infernal_mobs.java:1853) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.lambda$makeInfernal$0(infernal_mobs.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-39]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-39]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-39]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-39]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-39]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-39]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-39]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by FabioZumbi12** [comment]
Hi,

Please, try this version:

[InfernalMobs_6.1.zip](https://github.com/FabioZumbi12/InfernalMobs/files/4869676/InfernalMobs_6.1.zip)

**Comment by fonkfader** [comment]
thanks i try this version, i'll make you a return

**Comment by FabioZumbi12** [comment]
Ok, waiting your tests

**Comment by fonkfader** [comment]
still have an issue :
`[21:31:42 WARN]: [InfernalMobs] Task #543500 for InfernalMobs v6.1 generated an exception
java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_252]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilities(infernal_mobs.java:1861) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilitiesAmount(infernal_mobs.java:1853) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.lambda$makeInfernal$0(infernal_mobs.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-44]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-44]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by FabioZumbi12** [comment]
wut, try this build again: 
[InfernalMobs_6.1.zip](https://github.com/FabioZumbi12/InfernalMobs/files/4871250/InfernalMobs_6.1.zip)

**Comment by fonkfader** [comment]
still here :

`java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_252]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilities(infernal_mobs.java:1861) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilitiesAmount(infernal_mobs.java:1853) ~[?:?]
        at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.lambda$makeInfernal$0(infernal_mobs.java:300) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-44]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-44]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-44]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by ghost** [comment]
> wut, try this build again:
> [InfernalMobs_6.1.zip](https://github.com/FabioZumbi12/InfernalMobs/files/4871250/InfernalMobs_6.1.zip)

I've tried using the linked jar as well to where I'm getting the below spam in console:

```
04.08 11:22:05 [Server] WARN [InfernalMobs] Task #4860289 for InfernalMobs v6.1 generated an exception
04.08 11:22:05 [Server] INFO java.lang.IllegalArgumentException: bound must be positive
04.08 11:22:05 [Server] INFO at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_251]
04.08 11:22:05 [Server] INFO at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilities(infernal_mobs.java:1861) ~[?:?]
04.08 11:22:05 [Server] INFO at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.getAbilitiesAmount(infernal_mobs.java:1853) ~[?:?]
04.08 11:22:05 [Server] INFO at io.hotmail.com.jacob_vejvoda.infernal_mobs.infernal_mobs.lambda$makeInfernal$0(infernal_mobs.java:300) ~[?:?]
04.08 11:22:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
04.08 11:22:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```
